dist: bionic
sudo: required

branches:
  only:
    - master

language: cpp

os:
  - linux

compiler:
  - gcc

env:
  - TARGET_CPU=amd64 BUILD_TYPE=Debug
  - TARGET_CPU=amd64 BUILD_TYPE=Release

script:
  - cmake . -Bbuild -DBUILD_TESTS=ON
  - make -C build
  - build/Tests